name: matched-social-media-profile
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=20.3.3
  - r-base=4.1.3
  - r-essentials=4.1
  - r-languageserver=0.3.13
  - r-httpgd=1.3.0 # linux only
  - radian=0.6.3
